AWSTemplateFormatVersion: 2010-09-09
Description: Amazon EKS Deployment
Parameters:
  IpAddress:
    Description: Your IP Address (Not CIDR notation).
    Type: String
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: must be a valid IP address of the form x.x.x.x.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "User Access Configuration"
        Parameters:
          - IpAddress
    ParameterLabels:
      IpAddress:
        default: "IP Address"
Mappings:
  RegionMap: 
    us-east-2:  # Ohio
      AMI: ami-09eda8943319241d7
Resources:
    
Outputs:
